
# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:

# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        s_list = list(s)
        t_list = list(t)

        # print('s_list is : ', s_list)
        # print('t_list is : ', t_list)

        for index, char in enumerate(s):
            # print('char is : ' , char)
            if char in t_list:
                t_list.remove(char)
                # print('t_list is : ', t_list)

                
        return ''.join(t_list)

if __name__ == '__main__':
    solx = Solution()
    diff = solx.findTheDifference("a", "aa")
    print('diff is : ', diff)